from django.urls import path
from . import views

urlpatterns = [ 
    path("", views.Home, name = "home"),  
    path("browse/", views.Browse, name = "browse"),
    path("monsters", views.Monsters, name = "monsters"),
    path("browsebyspecies/", views.BrowseBySpecies, name = "browsebyspecies"),
    path("fishnsharks/", views.FishAndSharks, name = "fishnsharks"),
    path("dolphinsnporpoises/", views.DolphinsAndPorpoises, name = "dolphinsnporpoises"),
    path("sealsnsealions/", views.SealsAndSeaLions, name = "sealsnsealions"),
    path("viewallspecies/", views.ViewAllSpecies, name = "viewallspecies"),
    path("whales/", views.Whales, name = "whales"),
    path("seaturtles/", views.SeaTurtles, name = "seaturtles"),
    path("coral/", views.Coral, name = "coral"), 
    path("seabirds/", views.SeaBirbs, name = "seabirds"), 
    path("invertebrates/", views.Invertebrates, name = "invertebrates"),
    path("highlymigratoryspecies/", views.HighlyMigratorySpecies, name = "highlymigratoryspecies"),
    path("browsebyregion/", views.BrowseByRegion, name = "browsebyregion"),
    path("alaska/", views.Alaska, name = "alaska"),
    path("southeast/", views.SouthEast, name = "southeast"),
    path("newenglandmidatlantic/", views.NewEnglandMidAtlantic, name = "newenglandmidatlantic"),
    path("westcoast/", views.WestCoast, name = "westcoast"),
    path("pacificislands/", views.PacificIslands, name = "pacificislands"), 
    path("foreign/", views.Foreign, name = "foreign"), 
    path("browsebyendangeredstatus/", views.BrowseByEndangeredStatus, name = "browsebyendangeredstatus"),
    path("leastconcern/", views.LeastConcern, name = "leastconcern"),
    path("endangered/", views.Endangered, name = "endangered"), 
    path("nearthreatened/", views.NearThreatened, name = "nearthreatened"),
    path("criticallyendangered/", views.CriticallyEndangered, name = "criticallyendangered"), 
    path("datadeficient/", views.DataDeficient, name = "datadeficient"),
    path("vulnerable/", views.Vulnerable, name = "vulnerable"), 
    path("conmea/", views.ConMea, name = "conmea"),
    path("profile/", views.ProfilePage, name='profile'),
    path("activate/<uidb64>/<token>", views.Activate, name = "activate"),
    path('changepassword/', views.ChangePassword, name='changepassword'),
    path("signin/", views.SignIn, name = "signin"),
    path("signup/", views.SignUp, name = "signup"),
    path("logout/", views.Logout, name = "logout"), 
    path("speciesdata/", views.SpeciesApiData, name = "speciesdata"), 
    path("endangeredstatusdata/", views.EndangeredStatusScraper, name="endangeredstatusdata"),
    path("conservationmeasuresdata/", views.ConservationMeasuresScraper, name="conservationmeasuresdata"),
    path("imagescaper/", views.ImageScraper, name="imagescraper"),
    path("species/<int:speciesId>/", views.SpeciesCard, name="speciescard"),
    path("search/", views.Search, name="search"),
    path('species/heatmap/', views.SpeciesHeatMap, name='speciesheatmap')
    ]
