# Generated by Django 5.0.4 on 2024-05-19 22:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aquadex", "0002_alter_species_avglitsize_alter_species_numofspecies"),
    ]

    operations = [
        migrations.RenameField(
            model_name="species",
            old_name="kindom",
            new_name="kingdom",
        ),
    ]
