# Generated by Django 5.0.4 on 2024-05-20 01:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aquadex", "0003_rename_kindom_species_kingdom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="species",
            name="conmea",
        ),
        migrations.RemoveField(
            model_name="species",
            name="heatMap",
        ),
        migrations.RemoveField(
            model_name="species",
            name="img",
        ),
        migrations.RemoveField(
            model_name="species",
            name="status",
        ),
        migrations.AddField(
            model_name="species",
            name="locations",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="ageOfWeaning",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="avgLitSize",
            field=models.SmallIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(50),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="biggestThreat",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="clss",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="color",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="diet",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="distinctiveFeature",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="family",
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="favFood",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="genus",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="gestationPeriod",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="groupBehavior",
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="habitat",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="kingdom",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="length",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="lifespan",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="lifestyle",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="mostDistinctiveFeature",
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="name",
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name="species",
            name="nameOfYoung",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="numOfSpecies",
            field=models.SmallIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(50),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="optimumPhLvl",
            field=models.SmallIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(14),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="order",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="otherName",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="phylum",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="popSize",
            field=models.BigIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000000000000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="predators",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="prey",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="scientificName",
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="sexualMaturity",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="skinType",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="slogan",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="topSpeed",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="weight",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
