# Generated by Django 5.0.4 on 2024-05-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aquadex", "0005_remove_species_ageofweaning_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
