# Generated by Django 5.0.4 on 2024-06-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aquadex", "0006_alter_species_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="images",
            old_name="name",
            new_name="commonName",
        ),
        migrations.AddField(
            model_name="images",
            name="scientificName",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="images",
            name="img",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
