# Generated by Django 5.0.4 on 2024-06-01 04:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "aquadex",
            "0007_rename_name_images_commonname_images_scientificname_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="images",
            old_name="commonName",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="images",
            name="scientificName",
        ),
    ]
