# Generated by Django 5.0.4 on 2024-06-04 20:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aquadex", "0008_rename_commonname_images_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HeatMaps",
        ),
    ]
