# Generated by Django 5.0.4 on 2024-07-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aquadex", "0009_delete_heatmaps"),
    ]

    operations = [
        migrations.AddField(
            model_name="conservationmeasures",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="endangeredstatus",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="endangeredstatus",
            name="status",
            field=models.CharField(max_length=100),
        ),
    ]
